version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    networks:
      - my-app-network
    volumes:
      - sqlserver-data:/var/opt/mssql

  web:
    build: .
    ports:
      - "80:80"
    networks:
      - my-app-network
    depends_on:
      - sqlserver
    volumes:
      - web-data:/app

networks:
  my-app-network:
    driver: bridge

volumes:
  sqlserver-data:
  web-data: