version: "3.8"
services:
  mywebsite:
    image: tuananhpro/todoapp-docker:latest
    ports:
      - "80:80"
#      - "8081:443"
#    environment:
#      ASPNETCORE_URLS: "https://+;http://+"
#      ASPNETCORE_HTTPS_PORT: "8081"
